services:
  postgres:
    image: postgres:15
    container_name: td2_postgres
    environment:
      POSTGRES_USER: td2
      POSTGRES_PASSWORD: td2
      POSTGRES_DB: td2_builder
    ports:
      - "5482:5432"
    volumes:
      - td2_pgdata:/var/lib/postgresql/data

volumes:
  td2_pgdata:
